package day8

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class Day8Test {
    private val testInput = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent().split('\n')

    @Test
    fun part1() {
        assertEquals(14, part1(testInput))
    }

    @Test
    fun part2() {
        assertEquals(34, part2(testInput))
    }
}